//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklad_project_app {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sklad_project_app.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        internal static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОТМЕНА.
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗАКРЫТЬ.
        /// </summary>
        internal static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        internal static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        internal static string BtnLogout {
            get {
                return ResourceManager.GetString("BtnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        internal static string BtnRefresh {
            get {
                return ResourceManager.GetString("BtnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить.
        /// </summary>
        internal static string BtnReset {
            get {
                return ResourceManager.GetString("BtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СОХРАНИТЬ.
        /// </summary>
        internal static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотреть.
        /// </summary>
        internal static string BtnView {
            get {
                return ResourceManager.GetString("BtnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ООО &quot;Птички-тупички&quot; - система управления складом.
        /// </summary>
        internal static string CatalogCompany {
            get {
                return ResourceManager.GetString("CatalogCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каталог товаров.
        /// </summary>
        internal static string CatalogTitle {
            get {
                return ResourceManager.GetString("CatalogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Артикул.
        /// </summary>
        internal static string ColArticle {
            get {
                return ResourceManager.GetString("ColArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория.
        /// </summary>
        internal static string ColCategory {
            get {
                return ResourceManager.GetString("ColCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование товара.
        /// </summary>
        internal static string ColName {
            get {
                return ResourceManager.GetString("ColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена закупки.
        /// </summary>
        internal static string ColPrice {
            get {
                return ResourceManager.GetString("ColPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остаток.
        /// </summary>
        internal static string ColRest {
            get {
                return ResourceManager.GetString("ColRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ед. измерения.
        /// </summary>
        internal static string ColUnit {
            get {
                return ResourceManager.GetString("ColUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все категории.
        /// </summary>
        internal static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наличие:.
        /// </summary>
        internal static string FilterAvailability {
            get {
                return ResourceManager.GetString("FilterAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        internal static string FilterAvailAll {
            get {
                return ResourceManager.GetString("FilterAvailAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В наличии.
        /// </summary>
        internal static string FilterAvailIn {
            get {
                return ResourceManager.GetString("FilterAvailIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет в наличии.
        /// </summary>
        internal static string FilterAvailOut {
            get {
                return ResourceManager.GetString("FilterAvailOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория:.
        /// </summary>
        internal static string FilterCategory {
            get {
                return ResourceManager.GetString("FilterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена:.
        /// </summary>
        internal static string FilterPrice {
            get {
                return ResourceManager.GetString("FilterPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск (название / артикул):.
        /// </summary>
        internal static string FilterSearch {
            get {
                return ResourceManager.GetString("FilterSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администратор:.
        /// </summary>
        internal static string LblAdmin {
            get {
                return ResourceManager.GetString("LblAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найдено:.
        /// </summary>
        internal static string LblFoundFormat {
            get {
                return ResourceManager.GetString("LblFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на из.
        /// </summary>
        internal static string LblFoundOf {
            get {
                return ResourceManager.GetString("LblFoundOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кладовщик:.
        /// </summary>
        internal static string LblStorekeeper {
            get {
                return ResourceManager.GetString("LblStorekeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВЗЯТО ТОВАРОВ:.
        /// </summary>
        internal static string LblTotalItems {
            get {
                return ResourceManager.GetString("LblTotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль:.
        /// </summary>
        internal static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        internal static string LoginRegister {
            get {
                return ResourceManager.GetString("LoginRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВХОД В СИСТЕМУ.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя:.
        /// </summary>
        internal static string LoginUsername {
            get {
                return ResourceManager.GetString("LoginUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такая категория уже существует!.
        /// </summary>
        internal static string MsgCategoryExists {
            get {
                return ResourceManager.GetString("MsgCategoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нельзя удалить категорию — в ней есть товары!.
        /// </summary>
        internal static string MsgCategoryHasProducts {
            get {
                return ResourceManager.GetString("MsgCategoryHasProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория или единица измерения не найдены!.
        /// </summary>
        internal static string MsgCatUnitNotFound {
            get {
                return ResourceManager.GetString("MsgCatUnitNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название клиента!.
        /// </summary>
        internal static string MsgClientEmpty {
            get {
                return ResourceManager.GetString("MsgClientEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка подключения:.
        /// </summary>
        internal static string MsgConnectError {
            get {
                return ResourceManager.GetString("MsgConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключение успешно!.
        /// </summary>
        internal static string MsgConnectOk {
            get {
                return ResourceManager.GetString("MsgConnectOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить выбранный товар?.
        /// </summary>
        internal static string MsgDeleteConfirm {
            get {
                return ResourceManager.GetString("MsgDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение.
        /// </summary>
        internal static string MsgDeleteTitle {
            get {
                return ResourceManager.GetString("MsgDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заполните все поля!.
        /// </summary>
        internal static string MsgFillFields {
            get {
                return ResourceManager.GetString("MsgFillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка ввода.
        /// </summary>
        internal static string MsgInputError {
            get {
                return ResourceManager.GetString("MsgInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена не может быть отрицательной!.
        /// </summary>
        internal static string MsgNegativePrice {
            get {
                return ResourceManager.GetString("MsgNegativePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товары для отгрузки!.
        /// </summary>
        internal static string MsgNoItems {
            get {
                return ResourceManager.GetString("MsgNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно товара на складе!.
        /// </summary>
        internal static string MsgNotEnough {
            get {
                return ResourceManager.GetString("MsgNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректную цену!.
        /// </summary>
        internal static string MsgPriceError {
            get {
                return ResourceManager.GetString("MsgPriceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар добавлен!.
        /// </summary>
        internal static string MsgProductAdded {
            get {
                return ResourceManager.GetString("MsgProductAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка выбора товара!.
        /// </summary>
        internal static string MsgProductError {
            get {
                return ResourceManager.GetString("MsgProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар обновлён!.
        /// </summary>
        internal static string MsgProductUpdated {
            get {
                return ResourceManager.GetString("MsgProductUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация успешна! Логин:.
        /// </summary>
        internal static string MsgRegSuccess {
            get {
                return ResourceManager.GetString("MsgRegSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректный остаток!.
        /// </summary>
        internal static string MsgRestError {
            get {
                return ResourceManager.GetString("MsgRestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роль не найдена в базе данных!.
        /// </summary>
        internal static string MsgRoleNotFound {
            get {
                return ResourceManager.GetString("MsgRoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка сохранения:.
        /// </summary>
        internal static string MsgSaveError {
            get {
                return ResourceManager.GetString("MsgSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товар для удаления!.
        /// </summary>
        internal static string MsgSelectDelete {
            get {
                return ResourceManager.GetString("MsgSelectDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товар для редактирования!.
        /// </summary>
        internal static string MsgSelectEdit {
            get {
                return ResourceManager.GetString("MsgSelectEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товар!.
        /// </summary>
        internal static string MsgSelectProduct {
            get {
                return ResourceManager.GetString("MsgSelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите роль!.
        /// </summary>
        internal static string MsgSelectRole {
            get {
                return ResourceManager.GetString("MsgSelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товар для просмотра!.
        /// </summary>
        internal static string MsgSelectView {
            get {
                return ResourceManager.GetString("MsgSelectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отгрузка успешно оформлена!.
        /// </summary>
        internal static string MsgShipSuccess {
            get {
                return ResourceManager.GetString("MsgShipSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь с таким ФИО уже существует!.
        /// </summary>
        internal static string MsgUserExists {
            get {
                return ResourceManager.GetString("MsgUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный логин или пароль!.
        /// </summary>
        internal static string MsgWrongLogin {
            get {
                return ResourceManager.GetString("MsgWrongLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДОБАВЛЕНИЕ ТОВАРА.
        /// </summary>
        internal static string PanelAdd {
            get {
                return ResourceManager.GetString("PanelAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РЕДАКТИРОВАНИЕ ТОВАРА.
        /// </summary>
        internal static string PanelEdit {
            get {
                return ResourceManager.GetString("PanelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОСМОТР ТОВАРА.
        /// </summary>
        internal static string PanelView {
            get {
                return ResourceManager.GetString("PanelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администратор.
        /// </summary>
        internal static string RegisterAdmin {
            get {
                return ResourceManager.GetString("RegisterAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите нужное:.
        /// </summary>
        internal static string RegisterChoose {
            get {
                return ResourceManager.GetString("RegisterChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите ФИО:.
        /// </summary>
        internal static string RegisterFio {
            get {
                return ResourceManager.GetString("RegisterFio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите пароль:.
        /// </summary>
        internal static string RegisterPassword {
            get {
                return ResourceManager.GetString("RegisterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кладовщик.
        /// </summary>
        internal static string RegisterStorekeeper {
            get {
                return ResourceManager.GetString("RegisterStorekeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РЕГИСТРАЦИЯ В СИСТЕМЕ.
        /// </summary>
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
    }
}
